version: '3.4'

services:
  webapp:
    build:
      context: ./webapp
      target: dev
    ports:
      - "3000:80"
    volumes:
      - ./webapp:/opt

  event-bus:
    build:
      context: ./event-bus
      target: dev
    ports:
      - "8080:8080"
    volumes:
      - ./event-bus:/opt
    networks:
      - eventBus

  comment-moderation:
    build:
      context: ./comment-moderation
      target: dev
    ports:
      - "8002:8002"
    volumes:
      - ./comment-moderation:/opt

  comments:
    build:
      context: ./comments
      target: dev
    ports:
      - "8001:8001"
    volumes:
      - ./comments:/opt

  posts:
    build:
      context: ./posts
      target: dev
    ports:
      - "8000:8000"
    volumes:
      - ./posts:/opt

  query:
    depends_on:
      - "event-bus"
    build:
      context: ./query
      target: dev
    ports:
      - "8010:8010"
    volumes:
      - ./query:/opt
    networks:
      - eventBus

networks:
    eventBus:
