apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./_infra/k8s/* # manage these k8s files
build:
  local:
    push: false # do not push all changes to docker-hub
  artifacts:
    - image: vincentza/client
      context: webapp
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: . # auto rebuild image if file change isn't 'src/**/*.js', otherwise update pod with changes
    - image: vincentza/comment-moderation
      context: comment-moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: vincentza/comments
      context: comments
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: vincentza/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: vincentza/posts
      context: posts
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
    - image: vincentza/query
      context: query
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '**/*.js'
            dest: .
