apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-bus-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-bus
  template:
    metadata:
      labels:
        app: event-bus
    spec:
      containers:
      - name: posts
        image: vincentza/posts
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: event-bus-serv
spec:
  type: ClusterIP
  selector:
    app: event-bus
  ports:
  - name: event-bus
    protocol: TCP
    port: 8080
    targetPort: 8080
