apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-serv
  annotations:
    kubernetes.io/ingress.class: nginx # tells the ingress controller to expect routing rules
spec:
  rules:
    - host: posts.com # in etc/hosts have this url route to minikube IP or 127.0.0.1 if not
      http:
        paths:
          - path: /posts
            pathType: Prefix
            backend:
              service:
                name: posts-serv-clusterip
                port:
                  number: 8000
