apiVersion: apps/v1
kind: Deployment
metadata:
  name: posts-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: posts # manage pods with label app:posts
  template:
    metadata:
      labels:
        app: posts # create pod with label app:posts
    spec:
      containers:
      - name: posts
        image: vincentza/posts
        # imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
